### ISSUE TITLE
Stamina regen while swimming

### ISSUE THREAD

**Issue by sebacame** [humansandbag/Valheim-Better-Diving-Mod#2]
You can regen stamine while swimming if you use the "autowalk" keybind(Default Q), i guess stamina regen checks for WASD keys but not actual movement

**Comment by humansandbag** [comment]
Thank you. I will look into this issue.

**Comment by PaloAlo** [comment]
if you dive into water activate the dive feature and just swim back to shore you just have infinite stamina on land
that is till you type in chat with /s
then its back to normal
might be because you are supposed to be able to regain stamina standing still in water

this was in version 101,,, havent updated server yet to 102

update: i just updated the server to accept v1.0.2 so i will test and let you know

**Comment by humansandbag** [comment]
> You can regen stamine while swimming if you use the "autowalk" keybind(Default Q), i guess stamina regen checks for WASD keys but not actual movement

I have implemented a fix for this that will be released in version 1.0.3. The resting state will now be triggered when the players velocity is below a certain threshold. This mean that large waves (like those during thunderstorms) will also be able to hinder the players ability to regain stamina in the water.

**Comment by humansandbag** [comment]
I have released v1.0.3 that includes the fix for this bug.
