### ISSUE TITLE
No health depletion when out of stamina and breath

### ISSUE THREAD

**Issue by Re-nard** [humansandbag/Valheim-Better-Diving-Mod#5]
Good evening 😄 
The title says it all. I just DL your (very cool) mod to test the fog thickness factors and I realized I wasn't losing health when out of breath and stamina.
Devcommands/on and ghost mode/on but that's all.

If you need more details (mod list, .mp4 of the bug, anything) just hit me up I'll be glad to help !

**Comment by humansandbag** [comment]
Thanks for taking the time to submit a potential bug. This mod does not modify the health drain code in any way and relies on the vanilla code for that. So, unfortunately, there's nothing I can do about this issue. Cheats may prevent the player from dying in general even without the mod. Since you have devcommands enabled and the player is not losing health, I'll assume that you have a cheat enabled that prevents health drain. Otherwise, if you're using another mod that modifies the players health drain code, that other mod may be the cause and you'll need to submit an issue on that mods github.

**Comment by Re-nard** [comment]
Hi again 😄 !
Thanks for the reply !
I found out the issue : in ghost mod, you don't lose health when drowning. That's... unexpected but ok.
Sorry for the inconvenience and have a nice day !
